# Generated by Django 5.2.4 on 2025-07-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_reparation_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointdecontrole',
            name='permettre_fichiers',
            field=models.BooleanField(default=False, help_text="Autoriser l'ajout des fichiers."),
        ),
    ]
