# Generated by Django 5.2.4 on 2025-07-10 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pointdecontrole_permettre_fichiers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichiermedia',
            name='coordonnees_gps',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='fichiermedia',
            name='metadonnees',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='fichiermedia',
            name='statut_traitement',
            field=models.CharField(default='EN_COURS', max_length=20),
        ),
        migrations.AddField(
            model_name='fichiermedia',
            name='taille_compresse',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fichiermedia',
            name='taille_originale',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fichiermedia',
            name='duree_seconde',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fichiermedia',
            name='resolution',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AnnotationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_annotation', models.CharField(max_length=20)),
                ('donnees_svg', models.TextField()),
                ('couleur', models.CharField(default='#FF0000', max_length=7)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fichiermedia')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrouillonIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees_json', models.JSONField(default=dict)),
                ('derniere_modification', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('rapport_execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.rapportexecution')),
            ],
        ),
    ]
