# Generated by Django 5.2.4 on 2025-07-12 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fichiermedia_coordonnees_gps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichiermedia',
            name='uploade_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a uploadé ce média', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias_uploades', to=settings.AUTH_USER_MODEL),
        ),
    ]
